const LEAD_GET_REQUEST = 'LEAD_GET_REQUEST'
const LEAD_GET_SUCCESS = 'LEAD_GET_SUCCESS'
const LEAD_GET_ERROR = 'LEAD_GET_ERROR'

export default {
  LEAD_GET_REQUEST,
  LEAD_GET_SUCCESS,
  LEAD_GET_ERROR
}
