const LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const LOGIN_ERROR = 'USER_LOGIN_ERROR'
const LOGOUT = 'USER_LOGOUT'
const SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
const SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
const SIGNUP_ERROR = 'USER_SIGNUP_ERROR'
const GETME = 'USER_GETME'
const INIT_STORE='INIT_STORE'
const SUCCESSORS_SUCCESS='SUCCESSORS_SUCCESS'
const DETECT_DEVICE = 'DETECT_DEVICE'
export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGOUT,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_ERROR,
  GETME,
  INIT_STORE,
  SUCCESSORS_SUCCESS,
  DETECT_DEVICE
}
